name: Test Action

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test action with dry run
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          days: 30
          dry-run: 'true'

      # Additional test cases can be added here
      - name: Test with custom package name (dry run)
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: 'test-package'
          days: 14
          dry-run: 'true'

      # Optional: Add integration test that creates a test package and then deletes it
      # This would require additional setup steps
